// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const colors = {
 "sidebarBg": "rgba(54, 55, 64, 1)",
 "accentDisabled": "rgba(231, 234, 255, 1)",
 "accentDark": "rgba(37, 61, 217, 1)",
 "accentLight": "rgba(221, 226, 255, 0.9)",
 "accentDefault": "rgba(55, 81, 255, 1)",
 "yellowLight": "rgba(255, 237, 178, 1)",
 "yellowDefault": "rgba(254, 196, 0, 1)",
 "redDefault": "rgba(241, 43, 44, 1)",
 "greenDefault": "rgba(41, 204, 151, 1)",
 "greenLight": "rgba(212, 245, 234, 1)",
 "grayscaleExtraLight": "rgba(252, 253, 254, 1)",
 "grayscaleBg": "rgba(247, 248, 252, 1)",
 "grayscaleGrayLightest": "rgba(240, 241, 247, 1)",
 "grayscaleDividerGraph": "rgba(235, 237, 240, 1)",
 "grayscaleDivider": "rgba(223, 224, 235, 1)",
 "grayscaleGrayLight": "rgba(197, 199, 205, 1)",
 "grayscaleGray": "rgba(159, 162, 180, 1)",
 "grayscaleGrayDark": "rgba(75, 80, 109, 1)",
 "grayscaleWhite": "rgba(255, 255, 255, 1)",
 "grayscaleBlack": "rgba(51, 51, 51, 1)"
}

module.exports = colors;