// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const fontFamilies = {
 "bold": "Mulish",
 "medium": "Mulish",
 "regular": "Mulish",
 "light": "Mulish"
}

module.exports = fontFamilies;