// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const fontSizes = {
 "size40": "2.5rem",
 "size24": "1.5rem",
 "size19": "1.1875rem",
 "size16": "0.875rem",
 "size14": "0.875rem",
 "size12": "0.75rem",
 "size11": "0.6875rem",
 "size10": "0.625rem"
}

module.exports = fontSizes;